UserMVC/Models/Car.cs
namespace UserMVC.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }

        public int UserId { get; set; }
        public string ImgPath { get; set; }
        public IFormFile File { get; set; }
    }
}

UserMVC/Controllers/CarController.cs
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserMVC.Models;
using UserMVC.Services;
using UserMVC.ViewModels;

namespace UserMVC.Controllers
{
   
    public class CarController : Controller
    {

    private readonly ICarService _carService;
    private readonly IUserService _userService;

        public CarController(ICarService carService,IUserService userService)
    {
        _carService = carService;
        _userService = userService;
    }
       
        

        public async Task<IActionResult> List()
        {
            await _carService.Initdata();
            var res = await _carService.GetList();
            return View(res);

        }
        [HttpGet]
        public async Task<IActionResult> Insert()
        {
           
            Car car = new Car();
            ViewBag.Users =await _userService.GetList() ;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(Car car)
        {
            if (car.File == null || car.File.Length == 0)
                return BadRequest("فایلی انتخاب نشده است.");

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", car.File.FileName);

            // ایجاد مسیر در صورت نبود پوشه
            var directory = Path.GetDirectoryName(path);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            // ذخیره فایل به صورت Stream



            using (var stream = new FileStream(path, FileMode.Create))
            {
                await car.File.CopyToAsync(stream);
            }
            car.ImgPath = "/img/"+ car.File.FileName;
            await _carService.Insert(car);
            return RedirectToAction("list");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            Car car = await _carService.Get(id);
            return View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Car car)
        {
            await _carService.Update(car);
           
            return RedirectToAction("list");

        }

        public async Task<IActionResult> Delete(int id)
        {
           await _carService.Delete(id);
            return RedirectToAction("list");
        }



    }
}

UserMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserMVC.DB;
using UserMVC.Models;
using UserMVC.Services;
//using UserMVC.Views.User;


namespace UserMVC.Controllers
{

    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        /// <summary>
        /// اکشن نمایش لیست
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> List()
        {
            await _userService.InitData();
            return View(await _userService.GetList());
        }

        [HttpGet]
        public ActionResult Insert()
        {
            User user = new User();
            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> Insert(User user)
        {
           
            await _userService.Insert(user);

            return RedirectToAction("list");
        }

        public async Task<ActionResult> Delete(int id)
        {
           await _userService.delete(id);
            return RedirectToAction("list");

        }

        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            var user =await _userService.Get(id);

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Update(User user)
        {
           await _userService.Update(user);
            return RedirectToAction("list");
        }

    }
}

UserMVC/Views/Car/Insert.cshtml
@model UserMVC.Models.Car

@using UserMVC.Models;

@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
    ViewData["Title"] = "درج خودروی جدید";
    var users = ViewBag.Users as List<UserMVC.Models.User>;
}

<h2 class="text-center mt-4">New Car</h2>

<form asp-action="Insert" asp-controller="Car" method="post" class="mt-3" enctype="multipart/form-data">
    <div class="mb-3">
        <label asp-for="Brand" class="form-label">برند</label>
        <input asp-for="Brand" value="sss" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Model" class="form-label">مدل</label>
        <input asp-for="Model" type="number" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Color" class="form-label">رنگ</label>
        <input asp-for="Color"  class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="File" class="form-label">تصویر</label>
        <input asp-for="File" class="form-control" />
     
    </div>
    <label>کاربر مرتبط</label>
    <select asp-for="UserId" class="form-control">
        <option value="">انتخاب کاربر</option>
        @foreach (var users in ViewBag.Users as List<UserMVC.Models.User>)
        {
            <option value="@users.Id">@users.Name </option>
        }
    </select>

    <button type="submit" class="btn btn-dark">ثبت خودرو</button>
</form>







@* <hr class="my-4" />

@if (users != null)
{
    <h4 class="text-center mb-3"> لیست کاربران ثبت شده</h4>
    <table class="table table-bordered table-striped text-center">
        <thead class="table-dark">
            <tr>
                <th>نام</th>
                
                <th>ایمیل</th>
               
                <th>سن</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var u in users)
            {
                <tr>
                    <td>@u.Name</td>
                    <td>@u.Email</td>
                    <td>@u.Age</td>
                    
                </tr>
            }
        </tbody>
    </table>
} *@

UserMVC/Views/Car/List.cshtml
@using UserMVC.ViewModels
@model List<VmCar>

<h2>لیست ماشین ها</h2>



@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>لیست کاربران</h2>
<table class="table table-dark table_striped mt-4">
    <thead>
    <tr>
        <th>شناسه</th>
        <th>برند</th>
        <th>مدل</th>
        <th>رنگ</th>
            <th>مالک</th>
            <th>تصویر</th>
        <th></th>       
    </tr>
    </thead>
    <tbody>
        @foreach (var u in Model)
        {
            <tr>
              <td>@u.Id</td> 
                <td>@u.Brand</td>
                <td>@u.Model</td>
                <td>@u.Color</td>
                <td>@u.UserName</td>
                <td><img style="width:50px;" src="@u.ImgPath" /> </td>
                <td><a href="/User/Delete/@u.Id">حذف</a><a href="/User/Update/@u.Id">ویرایش</a></td>
            </tr>
        }
    </tbody>
</table>

UserMVC/Views/Car/Update.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "به روز رسانی کاربر جدید";
}
@model Car
<h2 class="text-center mt-4">new user</h2>

<form asp-action="Update" asp-controller="User" method="post" class="mt-3">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Brand" class="form-label">برند</label>
        <input asp-for="Brand" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Model" class="form-label">مدل</label>
        <input asp-for="Model" type="number" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Color" class="form-label">رنگ</label>
        <input asp-for="Color" type="number" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="ImgPath" class="form-label">رنگ</label>
        <input asp-for="ImgPath" class="form-control" />
    </div>
    <button type="submit" class="btn btn-dark">ثبت کاربر</button>
</form>